### ISSUE TITLE
resunet++ issue due to layer normalization changes 

### ISSUE THREAD

**Issue by danifranco** [BiaPyX/BiaPy#95]
There is a problem when using resunet++ model due to changes made in the normalization layers:

```
[12:03:21.168539] ###############
[12:03:21.168552] # Build model #
[12:03:21.168563] ###############
Traceback (most recent call last):
  File "/data/dfranco/BiaPy/main.py", line 4, in <module>
    main()
  File "/data/dfranco/BiaPy/biapy/__init__.py", line 68, in main
    _biapy.run_job()
  File "/data/dfranco/BiaPy/biapy/_biapy.py", line 831, in run_job
    self.train()
  File "/data/dfranco/BiaPy/biapy/_biapy.py", line 204, in train
    self.workflow.train()
  File "/data/dfranco/BiaPy/biapy/engine/base_workflow.py", line 931, in train
    self.prepare_model()
  File "/data/dfranco/BiaPy/biapy/engine/base_workflow.py", line 849, in prepare_model
    ) = build_model(self.cfg, self.job_identifier, self.device)
  File "/data/dfranco/BiaPy/biapy/models/__init__.py", line 116, in build_model
    model = callable_model(**args)
  File "/data/dfranco/BiaPy/biapy/models/resunet++.py", line 163, in __init__
    self.aspp_bridge = ASPP(
TypeError: ASPP.__init__() got an unexpected keyword argument 'norm'
```

Please @iarganda @anepaniagua check this method and the rest of models and functions within [block.py](https://github.com/BiaPyX/BiaPy/blob/master/biapy/models/blocks.py) to ensure everything is adapted.

**Comment by iarganda** [comment]
Thanks for reporting! The bug should be fixed now (commit 6a3b7d8).

**Comment by danifranco** [comment]
There is still an issue when building the model with the default settings:

```
[22:18:51.168386] ###############
[22:18:51.168403] # Build model #
[22:18:51.168415] ###############
Traceback (most recent call last):
  File "/home/dfranco/anaconda3/envs/BiaPy_env2/lib/python3.10/site-packages/torchinfo/torchinfo.py", line 295, in forward_pass
    _ = model(*x, **kwargs)
  File "/home/dfranco/anaconda3/envs/BiaPy_env2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1716, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/dfranco/anaconda3/envs/BiaPy_env2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1768, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/data/dfranco/BiaPy/biapy/models/resunet++.py", line 265, in forward
    x = att(blocks[-i - 2], x)
  File "/home/dfranco/anaconda3/envs/BiaPy_env2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1716, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/dfranco/anaconda3/envs/BiaPy_env2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1768, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/data/dfranco/BiaPy/biapy/models/blocks.py", line 984, in forward
    out = self.conv_encoder(x1) + self.conv_decoder(x2)
  File "/home/dfranco/anaconda3/envs/BiaPy_env2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1716, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/dfranco/anaconda3/envs/BiaPy_env2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1768, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/dfranco/anaconda3/envs/BiaPy_env2/lib/python3.10/site-packages/torch/nn/modules/container.py", line 249, in forward
    input = module(input)
  File "/home/dfranco/anaconda3/envs/BiaPy_env2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1716, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/dfranco/anaconda3/envs/BiaPy_env2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1768, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/dfranco/anaconda3/envs/BiaPy_env2/lib/python3.10/site-packages/torch/nn/modules/batchnorm.py", line 193, in forward
    return F.batch_norm(
  File "/home/dfranco/anaconda3/envs/BiaPy_env2/lib/python3.10/site-packages/torch/nn/functional.py", line 2812, in batch_norm
    return torch.batch_norm(
RuntimeError: running_mean should contain 256 elements not 64

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/dfranco/BiaPy/main.py", line 4, in <module>
    main()
  File "/data/dfranco/BiaPy/biapy/__init__.py", line 68, in main
    _biapy.run_job()
  File "/data/dfranco/BiaPy/biapy/_biapy.py", line 831, in run_job
    self.train()
  File "/data/dfranco/BiaPy/biapy/_biapy.py", line 204, in train
    self.workflow.train()
  File "/data/dfranco/BiaPy/biapy/engine/base_workflow.py", line 953, in train
    self.prepare_model()
  File "/data/dfranco/BiaPy/biapy/engine/base_workflow.py", line 871, in prepare_model
    ) = build_model(self.cfg, self.job_identifier, self.device)
  File "/data/dfranco/BiaPy/biapy/models/__init__.py", line 281, in build_model
    summary(
  File "/home/dfranco/anaconda3/envs/BiaPy_env2/lib/python3.10/site-packages/torchinfo/torchinfo.py", line 223, in summary
    summary_list = forward_pass(
  File "/home/dfranco/anaconda3/envs/BiaPy_env2/lib/python3.10/site-packages/torchinfo/torchinfo.py", line 304, in forward_pass
    raise RuntimeError(
RuntimeError: Failed to run torchinfo. See above stack traces for more details. Executed layers up to: [ConvTranspose3d: 1, ResConvBlock: 2, Sequential: 3, ConvBlock: 4, Sequential: 5, Conv3d: 6, BatchNorm3d: 6, ELU: 6, ConvBlock: 4, Sequential: 5, Conv3d: 6, Sequential: 3, Conv3d: 4, BatchNorm3d: 4, SqExBlock: 2, AdaptiveAvgPool3d: 3, Sequential: 3, Linear: 4, ReLU: 4, Linear: 4, Sigmoid: 4, ResConvBlock: 2, Sequential: 3, BatchNorm3d: 4, ELU: 4, ConvBlock: 4, Sequential: 5, Conv3d: 6, BatchNorm3d: 6, ELU: 6, ConvBlock: 4, Sequential: 5, Conv3d: 6, Sequential: 3, Conv3d: 4, BatchNorm3d: 4, SqExBlock: 2, AdaptiveAvgPool3d: 3, Sequential: 3, Linear: 4, ReLU: 4, Linear: 4, Sigmoid: 4, MaxPool3d: 2, ResConvBlock: 2, Sequential: 3, BatchNorm3d: 4, ELU: 4, ConvBlock: 4, Sequential: 5, Conv3d: 6, BatchNorm3d: 6, ELU: 6, ConvBlock: 4, Sequential: 5, Conv3d: 6, Sequential: 3, Conv3d: 4, BatchNorm3d: 4, SqExBlock: 2, AdaptiveAvgPool3d: 3, Sequential: 3, Linear: 4, ReLU: 4, Linear: 4, Sigmoid: 4, MaxPool3d: 2, ResConvBlock: 2, Sequential: 3, BatchNorm3d: 4, ELU: 4, ConvBlock: 4, Sequential: 5, Conv3d: 6, BatchNorm3d: 6, ELU: 6, ConvBlock: 4, Sequential: 5, Conv3d: 6, Sequential: 3, Conv3d: 4, BatchNorm3d: 4, MaxPool3d: 2, ASPP: 1, Sequential: 2, Conv3d: 3, ReLU: 3, BatchNorm3d: 3, Sequential: 2, Conv3d: 3, ReLU: 3, BatchNorm3d: 3, Sequential: 2, Conv3d: 3, ReLU: 3, BatchNorm3d: 3, Conv3d: 2, Sequential: 3, BatchNorm3d: 4, ReLU: 4, Conv3d: 4, MaxPool3d: 4]
```

**Comment by iarganda** [comment]
Fixed in commit 3947425.
